### ISSUE TITLE
Class 'insolita\wgadminlte\SmallBox' not found

### ISSUE THREAD

**Issue by LarryTX** [dmstr/yii2-adminlte-asset#162]
When creating a module, the extension interjects this into the default index.php file:

```return '<div class="col-xs-6 col-sm-4 col-lg-3">'.insolita\wgadminlte\SmallBox::widget(```

which results in the following error message:

```Class 'insolita\wgadminlte\SmallBox' not found```

Any guidance on resolving this issue?

[index.zip](https://github.com/dmstr/yii2-adminlte-asset/files/1854627/index.zip)

**Comment by githubjeka** [comment]
Try `\insolita\wgadminlte\SmallBox` instead `insolita\wgadminlte\SmallBox`

**Comment by LarryTX** [comment]
Sorry, that made no difference at all.

Larry E. Lutz

**Comment by githubjeka** [comment]
Try to reinstall https://github.com/Insolita/yii2-adminlte-widgets#installation

**Comment by LarryTX** [comment]
I completely uninstalled it and reinstalled it. No change.

Larry E. Lutz

**Comment by githubjeka** [comment]
Class named as `LteSmallBox ` https://github.com/Insolita/yii2-adminlte-widgets/blob/master/LteSmallBox.php#L22

Try to use  `\insolita\wgadminlte\LteSmallBox` instead `insolita\wgadminlte\SmallBox`

**Comment by LarryTX** [comment]
Well, we may be getting someplace. At least the error message changed indicating that it’s finding the class. The new error message is:

                Setting unknown property: insolita\wgadminlte\LteSmallBox::footer_link

Larry E. Lutz

**Comment by LarryTX** [comment]
I commented out these two, and the page came up without error, but poorly formatted:

                // 'head'        => $data['head'],
                // 'footer_link' => $data['route'],

And, of course, the footer link doesn’t work, so the page is useless at this point.

Larry E. Lutz

**Comment by githubjeka** [comment]
In the future, please be attentive, especially since this is not our question, but the question from a completely different project ([Insolita/yii2-adminlte-widgets](https://github.com/Insolita/yii2-adminlte-widgets)). 
You can ask about your problems in the chat https://yii.slack.com/

Good luck with the business.

**Comment by schmunk42** [comment]
Insolita did some refactoring, you could also stay on `^1.1.4`, I think.

**Comment by LarryTX** [comment]
After all, it was the fact that your extension injected the call to the insolita extension that cause the entire problem in the first place. It seems to me that, if you’re gong to do that, the maintenance goes with you.

Larry E. Lutz

**Comment by schmunk42** [comment]
You mean this one? https://github.com/dmstr/yii2-adminlte-asset/blob/b0e225d670720e8885df7301a6558e03d645030b/example-views/testing/app/default/_controllers.php

It's meant as an example, see README

> Therefore it is recommended to copy the views into your application and adjust them to your needs.

But yes, also this can be improved. Let me know if there's another reference I am missing.

**Comment by maya-tsedeke** [comment]
dear larry-tx 
use insolita\wgadminlte\LteSmallBox instead of insolita\wgadminlte\SmallBox

then declare public variable find the following the declared as public your project  vendor/insolita\wgadminlte\LteSmallBox.php 
public $head may not be found in the latest version of insolita\wgadminlte\SmallBox
declare it as follows in vendor/insolita\wgadminlte\LteSmallBox.php

             public   $ type  
             public $head 
             public   $text       
             public     $footer    
              publick  footer_link  or   public $link = '#'; footer_link not found edit it to  public link = '#'; instead footer_link
                and 
public $con      

if  insolita\wgadminlte\SmallBox not found in the vendor install it via composer
php composer.phar require --prefer-dist insolita/yii2-adminlte-widgets
